In [29]:
import numpy as np

In [30]:
# 1. Cretion of a vector of length 5 filled with arbitrary numbers from 0 to 10.

vector = np.random.randint(0,11,5)
print(vector)

[6 7 0 1 4]


In [31]:
# 2. Writing of numpy program to create a vector of values ranging from 15 to 55 and printing
#     all values except the first and the last.

vector2 = np.arange(15,56)
print(vector2[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [32]:
# 3.a Writing of numpy program to create a random array with 1000 elements. 

arr1 = np.random.randint(1,100,1000)
print(arr1)

[43 93 24 87 25 58 51 82 70 68 78 73 84 22 80 85 70 79  6 49 61 93 67 85
 64 77 68 60 43 69 95 27 22  1 13 45 10 20  1 95 64 25 47 24 36 82 24 78
 24 95 56 16 13 10 24 21 38 63 46 22 69 32 60 50 61 73 67 74  3 26  2 72
 62 13 57 18 70 76 75 68  5 32 10 47 71 79 43 92 54 34 74 83 17 64 38 50
 48 46 34 73 82 31 57 14 56 67 28 73 82 21 27 88 99 90 94 71 24 11 30 74
 42 72  9 45 48 93 36 80 20 64 42 45 58 99 81 89 97 41 53 54 87 10 81  2
 42 34 73 59  4 97 43 56 87 27 61 45 54 81 76 58 50 41 87 31 48 81 27 35
 26 33 17  7 22 24  4 94 27 33  3 85 77 57 74 20 14 99 95  8 43 46 46  1
 51 69 18 56 38 78 58 16 98 15 47 77 41 56 87 81 51 52  6 16 82 77 86 74
 56  2 70 49 59 78 89 68 37 22 63 50 53 19 57 65 71 72 26 53 49 80  5  6
 18 89 12 73 88 47 95 54 83 55 99 33 48  1 22 23 31 98 13 59 59 74 99 12
  1 65 48  6 21 49 65 90 80 41 75  1 42 70 78 66  1 70 69  5  8 48 25 98
 53 76 52 18  9 91 73 79 90 83 72 72 12 27 97 93 19  9 10 43 42 63  9 19
 83 81 81 10 88 14 56 28 94 36 68 45 58 53 15  6 28

In [33]:
# 3.b Computing  the average, variance and standard deviation of the array elements.

avg = np.average(arr1)
print('Average\n', avg)

variance = np.var(arr1)
print('Variance\n', variance)

deviation = np.std(arr1)
print('Standard Deviation\n',deviation)

Average
 50.224
Variance
 792.155824
Standard Deviation
 28.145262905149778


In [34]:
# 4.a. A python program to calculate a cummulative sum of elements along a given axis,
#    Creation of 3x3 array.

arr = np.array([[1,2,3],[5,4,6],[9,8,7]])
print(arr)

[[1 2 3]
 [5 4 6]
 [9 8 7]]


In [35]:
# 4.b. Sum over rows for each of the 3 columns.

sum_rows = np.cumsum(arr, axis = 0)
print('Sum over rows\n',sum_rows)

Sum over rows
 [[ 1  2  3]
 [ 6  6  9]
 [15 14 16]]


In [36]:
# 4.c  Sum over columns for each of the 3 rows.
sum_cols = np.cumsum(arr, axis = 1)
print('Sum over columns\n', sum_cols)

Sum over columns
 [[ 1  3  6]
 [ 5  9 15]
 [ 9 17 24]]


In [37]:
# 5. Numpy program to compute the multiplication of two matrixes.

mat1 = np.array([[9,7],[3,2]])
mat2 = np.array([[4,6],[5,8]])
product = np.dot(mat1,mat2)
print(product)

[[ 71 110]
 [ 22  34]]
