In [1]:
import numpy as np
import pandas as pd

In [2]:
table = np.zeros((5,5),dtype=int)

In [3]:
table

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
table[0]=1
table[1][2]=0
table[1][4]=1
table[1][0]=1
table[2][1]=0
table[2][2]=9
table[2][4]=1
table[3][0]=1
table[3][4]=1
table[4]=1
print(table)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [11]:
pd.DataFrame(table)

0  1  2  3  4
0  1  1  1  1  1
1  1  0  0  0  1
2  1  0  9  0  1
3  1  0  0  0  1
4  1  1  1  1  1